<?xml version="1.0" encoding="ASCII"?>
<view:View xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:view="http://davidmoten.homeip.net/uml/executable/view" xsi:schemaLocation="http://davidmoten.homeip.net/uml/executable/view http://xuml-compiler.googlecode.com/svn/trunk/xUmlCompiler/src/viewer/model/viewer.ecore">
  <frame width="988" height="781" x="81" y="72"/>
  <viewport width="1000" height="1000"/>
  <element x="149" y="271" name="class.Book"/>
  <element x="233" y="397" name="label.Class Book Association R2 Multiplicity" fixedTo="//@element[name='class.Book']"/>
  <element x="306" y="331" name="label.Class Book Association R4 Multiplicity" fixedTo="//@element[name='class.Book']"/>
  <element x="191" y="395" name="label.Class Book Association R2 Verb Clause" fixedTo="//@element[name='class.Book']"/>
  <element x="154" y="235" name="label.Class Book Association R1 Verb Clause" fixedTo="//@element[name='class.Book']"/>
  <element x="304" y="306" name="label.Class Book Association R4 Verb Clause" fixedTo="//@element[name='class.Book']"/>
  <element x="236" y="244" name="label.Class Book Association R1 Multiplicity" fixedTo="//@element[name='class.Book']"/>
  <element x="167" y="564" name="class.Author"/>
  <element x="236" y="530" name="label.Class Author Association R2 Multiplicity" fixedTo="//@element[name='class.Author']"/>
  <element x="161" y="529" name="label.Class Author Association R2 Verb Clause" fixedTo="//@element[name='class.Author']"/>
  <element x="151" y="41" name="class.Publisher"/>
  <element x="237" y="140" name="label.Class Publisher Association R1 Multiplicity" fixedTo="//@element[name='class.Publisher']"/>
  <element x="144" y="145" name="label.Class Publisher Association R1 Verb Clause" fixedTo="//@element[name='class.Publisher']"/>
  <element x="316" y="450" name="class.Authorship"/>
  <element x="304" y="171" name="class.ProductSelection"/>
  <element x="476" y="28" name="class.Shipment"/>
  <element x="521" y="155" name="label.Class Shipment Association R6 Multiplicity" fixedTo="//@element[name='class.Shipment']"/>
  <element x="554" y="155" name="label.Class Shipment Association R6 Verb Clause" fixedTo="//@element[name='class.Shipment']"/>
  <element x="478" y="273" name="class.Order"/>
  <element x="560" y="400" name="label.Class Order Association R7 Multiplicity" fixedTo="//@element[name='class.Order']"/>
  <element x="500" y="399" name="label.Class Order Association R7 Verb Clause" fixedTo="//@element[name='class.Order']"/>
  <element x="467" y="335" name="label.Class Order Association R4 Multiplicity" fixedTo="//@element[name='class.Order']"/>
  <element x="533" y="239" name="label.Class Order Association R6 Multiplicity" fixedTo="//@element[name='class.Order']"/>
  <element x="631" y="293" name="label.Class Order Association R5 Verb Clause" fixedTo="//@element[name='class.Order']"/>
  <element x="554" y="240" name="label.Class Order Association R6 Verb Clause" fixedTo="//@element[name='class.Order']"/>
  <element x="631" y="313" name="label.Class Order Association R5 Multiplicity" fixedTo="//@element[name='class.Order']"/>
  <element x="399" y="308" name="label.Class Order Association R4 Verb Clause" fixedTo="//@element[name='class.Order']"/>
  <element x="777" y="293" name="class.Customer"/>
  <element x="713" y="308" name="label.Class Customer Association R5 Verb Clause" fixedTo="//@element[name='class.Customer']"/>
  <element x="752" y="331" name="label.Class Customer Association R5 Multiplicity" fixedTo="//@element[name='class.Customer']"/>
  <element x="470" y="527" name="class.CreditCardCharge"/>
  <element x="479" y="492" name="label.Class CreditCardCharge Association R7 Verb Clause" fixedTo="//@element[name='class.CreditCardCharge']"/>
  <element x="558" y="493" name="label.Class CreditCardCharge Association R7 Multiplicity" fixedTo="//@element[name='class.CreditCardCharge']"/>
  <element x="290" y="247" name="class.Order.state.Open"/>
  <element x="454" y="245" name="class.Order.state.Delivered"/>
  <element x="413" y="146" name="class.Order.state.FinalState"/>
  <element x="58" y="249" name="class.Order.state.Cancelled"/>
  <element x="197" y="150" name="class.Order.state.InitialState"/>
</view:View>
