<?xml version="1.0" encoding="ASCII"?>
<view:View xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:view="http://davidmoten.homeip.net/uml/executable/view" xsi:schemaLocation="http://davidmoten.homeip.net/uml/executable/view http://xuml-compiler.googlecode.com/svn/trunk/xUmlCompiler/src/viewer/model/viewer.ecore">
  <frame width="1288" height="998" x="-4" y="-4"/>
  <viewport width="1257" height="1200"/>
  <element x="496" y="287" name="class.Pkg"/>
  <element x="521" y="330" name="label.Class Pkg Association R13 Multiplicity" fixedTo="//@element[name='class.Pkg']"/>
  <element x="454" y="331" name="label.Class Pkg Association R13 Verb Clause" fixedTo="//@element[name='class.Pkg']"/>
  <element x="529" y="244" name="label.Class Pkg Association R14 Multiplicity Primary" fixedTo="//@element[name='class.Pkg']"/>
  <element x="494" y="258" name="label.Class Pkg Association R14 Verb Clause Primary" fixedTo="//@element[name='class.Pkg']"/>
  <element x="591" y="248" name="label.Class Pkg Association R14 Multiplicity Secondary" fixedTo="//@element[name='class.Pkg']"/>
  <element x="594" y="258" name="label.Class Pkg Association R14 Verb Clause Secondary" fixedTo="//@element[name='class.Pkg']"/>
  <element x="348" y="457" name="class.Clazz"/>
  <element x="295" y="489" name="label.Class Clazz Association R3 Verb Clause" fixedTo="//@element[name='class.Clazz']"/>
  <element x="419" y="522" name="label.Class Clazz Association R1 Multiplicity" fixedTo="//@element[name='class.Clazz']"/>
  <element x="497" y="500" name="label.Class Clazz Association R4 Verb Clause" fixedTo="//@element[name='class.Clazz']"/>
  <element x="550" y="433" name="label.Class Clazz Association R23 Verb Clause" fixedTo="//@element[name='class.Clazz']"/>
  <element x="438" y="392" name="label.Class Clazz Association R13 Verb Clause" fixedTo="//@element[name='class.Clazz']"/>
  <element x="474" y="396" name="label.Class Clazz Association R13 Multiplicity" fixedTo="//@element[name='class.Clazz']"/>
  <element x="262" y="417" name="label.Class Clazz Association R29 Verb Clause" fixedTo="//@element[name='class.Clazz']"/>
  <element x="344" y="400" name="label.Class Clazz Association R29 Multiplicity" fixedTo="//@element[name='class.Clazz']"/>
  <element x="539" y="470" name="label.Class Clazz Association R23 Multiplicity" fixedTo="//@element[name='class.Clazz']"/>
  <element x="485" y="512" name="label.Class Clazz Association R4 Multiplicity" fixedTo="//@element[name='class.Clazz']"/>
  <element x="331" y="509" name="label.Class Clazz Association R3 Multiplicity" fixedTo="//@element[name='class.Clazz']"/>
  <element x="382" y="406" name="label.Class Clazz Association R11 Verb Clause" fixedTo="//@element[name='class.Clazz']"/>
  <element x="412" y="406" name="label.Class Clazz Association R11 Multiplicity" fixedTo="//@element[name='class.Clazz']"/>
  <element x="377" y="518" name="label.Class Clazz Association R1 Verb Clause" fixedTo="//@element[name='class.Clazz']"/>
  <element x="133" y="405" name="class.AbstractClass"/>
  <element x="194" y="372" name="label.Class AbstractClass Association R7 Multiplicity" fixedTo="//@element[name='class.AbstractClass']"/>
  <element x="78" y="373" name="label.Class AbstractClass Association R7 Verb Clause" fixedTo="//@element[name='class.AbstractClass']"/>
  <element x="129" y="502" name="class.ConcreteClass"/>
  <element x="342" y="34" name="class.Association"/>
  <element x="370" y="71" name="label.Class Association Association R10 Multiplicity" fixedTo="//@element[name='class.Association']"/>
  <element x="399" y="91" name="label.Class Association Association R9 Verb Clause" fixedTo="//@element[name='class.Association']"/>
  <element x="307" y="67" name="label.Class Association Association R10 Verb Clause" fixedTo="//@element[name='class.Association']"/>
  <element x="470" y="44" name="label.Class Association Association R8 Verb Clause" fixedTo="//@element[name='class.Association']"/>
  <element x="458" y="91" name="label.Class Association Association R9 Multiplicity" fixedTo="//@element[name='class.Association']"/>
  <element x="460" y="65" name="label.Class Association Association R8 Multiplicity" fixedTo="//@element[name='class.Association']"/>
  <element x="350" y="296" name="class.AssociationEnd"/>
  <element x="415" y="331" name="label.Class AssociationEnd Association R11 Multiplicity" fixedTo="//@element[name='class.AssociationEnd']"/>
  <element x="326" y="330" name="label.Class AssociationEnd Association R11 Verb Clause" fixedTo="//@element[name='class.AssociationEnd']"/>
  <element x="202" y="194" name="class.AssociationEndPrimary"/>
  <element x="291" y="165" name="label.Class AssociationEndPrimary Association R9 Multiplicity" fixedTo="//@element[name='class.AssociationEndPrimary']"/>
  <element x="198" y="161" name="label.Class AssociationEndPrimary Association R9 Verb Clause" fixedTo="//@element[name='class.AssociationEndPrimary']"/>
  <element x="449" y="194" name="class.AssociationEndSecondary"/>
  <element x="438" y="163" name="label.Class AssociationEndSecondary Association R10 Verb Clause" fixedTo="//@element[name='class.AssociationEndSecondary']"/>
  <element x="550" y="162" name="label.Class AssociationEndSecondary Association R10 Multiplicity" fixedTo="//@element[name='class.AssociationEndSecondary']"/>
  <element x="304" y="648" name="class.Attribute"/>
  <element x="268" y="679" name="label.Class Attribute Association R22 Verb Clause" fixedTo="//@element[name='class.Attribute']"/>
  <element x="337" y="615" name="label.Class Attribute Association R1 Verb Clause" fixedTo="//@element[name='class.Attribute']"/>
  <element x="398" y="607" name="label.Class Attribute Association R12 Verb Clause" fixedTo="//@element[name='class.Attribute']"/>
  <element x="374" y="620" name="label.Class Attribute Association R1 Multiplicity" fixedTo="//@element[name='class.Attribute']"/>
  <element x="427" y="648" name="label.Class Attribute Association R12 Multiplicity" fixedTo="//@element[name='class.Attribute']"/>
  <element x="328" y="687" name="label.Class Attribute Association R22 Multiplicity" fixedTo="//@element[name='class.Attribute']"/>
  <element x="534" y="848" name="class.AttributeNormal"/>
  <element x="595" y="804" name="label.Class AttributeNormal Association R30 Multiplicity" fixedTo="//@element[name='class.AttributeNormal']"/>
  <element x="544" y="805" name="label.Class AttributeNormal Association R30 Verb Clause" fixedTo="//@element[name='class.AttributeNormal']"/>
  <element x="525" y="726" name="class.AttributeReferential"/>
  <element x="501" y="749" name="label.Class AttributeReferential Association R30 Verb Clause" fixedTo="//@element[name='class.AttributeReferential']"/>
  <element x="601" y="748" name="label.Class AttributeReferential Association R30 Multiplicity" fixedTo="//@element[name='class.AttributeReferential']"/>
  <element x="73" y="610" name="class.Operation"/>
  <element x="140" y="642" name="label.Class Operation Association R15 Multiplicity" fixedTo="//@element[name='class.Operation']"/>
  <element x="186" y="588" name="label.Class Operation Association R3 Multiplicity" fixedTo="//@element[name='class.Operation']"/>
  <element x="76" y="640" name="label.Class Operation Association R15 Verb Clause" fixedTo="//@element[name='class.Operation']"/>
  <element x="82" y="573" name="label.Class Operation Association R3 Verb Clause" fixedTo="//@element[name='class.Operation']"/>
  <element x="586" y="584" name="class.Identifier"/>
  <element x="556" y="591" name="label.Class Identifier Association R12 Verb Clause" fixedTo="//@element[name='class.Identifier']"/>
  <element x="579" y="543" name="label.Class Identifier Association R4 Verb Clause" fixedTo="//@element[name='class.Identifier']"/>
  <element x="573" y="569" name="label.Class Identifier Association R4 Multiplicity" fixedTo="//@element[name='class.Identifier']"/>
  <element x="578" y="611" name="label.Class Identifier Association R12 Multiplicity" fixedTo="//@element[name='class.Identifier']"/>
  <element x="97" y="265" name="class.SpecializationGroup"/>
  <element x="218" y="297" name="label.Class SpecializationGroup Association R29 Verb Clause" fixedTo="//@element[name='class.SpecializationGroup']"/>
  <element x="193" y="305" name="label.Class SpecializationGroup Association R29 Multiplicity" fixedTo="//@element[name='class.SpecializationGroup']"/>
  <element x="60" y="296" name="label.Class SpecializationGroup Association R7 Verb Clause" fixedTo="//@element[name='class.SpecializationGroup']"/>
  <element x="142" y="316" name="label.Class SpecializationGroup Association R7 Multiplicity" fixedTo="//@element[name='class.SpecializationGroup']"/>
  <element x="709" y="203" name="class.AssociationClass"/>
  <element x="633" y="172" name="label.Class AssociationClass Association R8 Verb Clause" fixedTo="//@element[name='class.AssociationClass']"/>
  <element x="736" y="170" name="label.Class AssociationClass Association R8 Multiplicity" fixedTo="//@element[name='class.AssociationClass']"/>
  <element x="77" y="788" name="class.OperationSignature"/>
  <element x="66" y="826" name="label.Class OperationSignature Association R16 Verb Clause" fixedTo="//@element[name='class.OperationSignature']"/>
  <element x="153" y="759" name="label.Class OperationSignature Association R15 Multiplicity" fixedTo="//@element[name='class.OperationSignature']"/>
  <element x="151" y="825" name="label.Class OperationSignature Association R16 Multiplicity" fixedTo="//@element[name='class.OperationSignature']"/>
  <element x="62" y="758" name="label.Class OperationSignature Association R15 Verb Clause" fixedTo="//@element[name='class.OperationSignature']"/>
  <element x="217" y="924" name="class.DataType"/>
  <element x="223" y="957" name="label.Class DataType Association R17 Multiplicity" fixedTo="//@element[name='class.DataType']"/>
  <element x="202" y="889" name="label.Class DataType Association R22 Verb Clause" fixedTo="//@element[name='class.DataType']"/>
  <element x="252" y="955" name="label.Class DataType Association R17 Verb Clause" fixedTo="//@element[name='class.DataType']"/>
  <element x="287" y="889" name="label.Class DataType Association R22 Multiplicity" fixedTo="//@element[name='class.DataType']"/>
  <element x="108" y="1087" name="class.Parameter"/>
  <element x="135" y="1032" name="label.Class Parameter Association R16 Verb Clause" fixedTo="//@element[name='class.Parameter']"/>
  <element x="212" y="1043" name="label.Class Parameter Association R17 Multiplicity" fixedTo="//@element[name='class.Parameter']"/>
  <element x="229" y="1067" name="label.Class Parameter Association R36 Verb Clause" fixedTo="//@element[name='class.Parameter']"/>
  <element x="239" y="1086" name="label.Class Parameter Association R36 Multiplicity" fixedTo="//@element[name='class.Parameter']"/>
  <element x="168" y="1035" name="label.Class Parameter Association R16 Multiplicity" fixedTo="//@element[name='class.Parameter']"/>
  <element x="217" y="1030" name="label.Class Parameter Association R17 Verb Clause" fixedTo="//@element[name='class.Parameter']"/>
  <element x="691" y="458" name="class.StateMachine"/>
  <element x="822" y="471" name="label.Class StateMachine Association R25 Multiplicity" fixedTo="//@element[name='class.StateMachine']"/>
  <element x="816" y="449" name="label.Class StateMachine Association R25 Verb Clause" fixedTo="//@element[name='class.StateMachine']"/>
  <element x="823" y="502" name="label.Class StateMachine Association R31 Multiplicity" fixedTo="//@element[name='class.StateMachine']"/>
  <element x="668" y="471" name="label.Class StateMachine Association R23 Multiplicity" fixedTo="//@element[name='class.StateMachine']"/>
  <element x="757" y="492" name="label.Class StateMachine Association R27 Multiplicity" fixedTo="//@element[name='class.StateMachine']"/>
  <element x="645" y="434" name="label.Class StateMachine Association R23 Verb Clause" fixedTo="//@element[name='class.StateMachine']"/>
  <element x="808" y="492" name="label.Class StateMachine Association R31 Verb Clause" fixedTo="//@element[name='class.StateMachine']"/>
  <element x="703" y="492" name="label.Class StateMachine Association R27 Verb Clause" fixedTo="//@element[name='class.StateMachine']"/>
  <element x="950" y="735" name="class.State"/>
  <element x="1021" y="703" name="label.Class State Association R33 Multiplicity" fixedTo="//@element[name='class.State']"/>
  <element x="960" y="699" name="label.Class State Association R33 Verb Clause" fixedTo="//@element[name='class.State']"/>
  <element x="827" y="662" name="class.FromState"/>
  <element x="881" y="687" name="label.Class FromState Association R32 Multiplicity" fixedTo="//@element[name='class.FromState']"/>
  <element x="905" y="680" name="label.Class FromState Association R32 Verb Clause" fixedTo="//@element[name='class.FromState']"/>
  <element x="728" y="808" name="class.TerminatingState"/>
  <element x="785" y="777" name="label.Class TerminatingState Association R27 Multiplicity" fixedTo="//@element[name='class.TerminatingState']"/>
  <element x="704" y="776" name="label.Class TerminatingState Association R27 Verb Clause" fixedTo="//@element[name='class.TerminatingState']"/>
  <element x="827" y="555" name="class.InitialState"/>
  <element x="854" y="525" name="label.Class InitialState Association R25 Verb Clause" fixedTo="//@element[name='class.InitialState']"/>
  <element x="822" y="533" name="label.Class InitialState Association R25 Multiplicity" fixedTo="//@element[name='class.InitialState']"/>
  <element x="438" y="962" name="class.FreeType"/>
  <element x="428" y="906" name="class.PrimitiveType"/>
  <element x="1042" y="458" name="class.Transition"/>
  <element x="1055" y="509" name="label.Class Transition Association R32 Multiplicity" fixedTo="//@element[name='class.Transition']"/>
  <element x="1034" y="471" name="label.Class Transition Association R31 Multiplicity" fixedTo="//@element[name='class.Transition']"/>
  <element x="1075" y="554" name="label.Class Transition Association R33 Multiplicity" fixedTo="//@element[name='class.Transition']"/>
  <element x="1020" y="541" name="label.Class Transition Association R33 Verb Clause" fixedTo="//@element[name='class.Transition']"/>
  <element x="1022" y="451" name="label.Class Transition Association R31 Verb Clause" fixedTo="//@element[name='class.Transition']"/>
  <element x="1133" y="505" name="label.Class Transition Association R35 Multiplicity" fixedTo="//@element[name='class.Transition']"/>
  <element x="1000" y="491" name="label.Class Transition Association R32 Verb Clause" fixedTo="//@element[name='class.Transition']"/>
  <element x="1133" y="491" name="label.Class Transition Association R35 Verb Clause" fixedTo="//@element[name='class.Transition']"/>
  <element x="1069" y="863" name="class.Event"/>
  <element x="1139" y="827" name="label.Class Event Association R35 Multiplicity" fixedTo="//@element[name='class.Event']"/>
  <element x="992" y="870" name="label.Class Event Association R36 Verb Clause" fixedTo="//@element[name='class.Event']"/>
  <element x="1063" y="893" name="label.Class Event Association R36 Multiplicity" fixedTo="//@element[name='class.Event']"/>
  <element x="1053" y="826" name="label.Class Event Association R35 Verb Clause" fixedTo="//@element[name='class.Event']"/>
  <element x="972" y="1010" name="class.CallEvent"/>
  <element x="1020" y="1095" name="class.TimerEvent"/>
  <element x="1171" y="1006" name="class.SignalEvent"/>
  <element x="1117" y="1095" name="class.ChangeEvent"/>
</view:View>
