<?xml version="1.0" encoding="ASCII"?>
<view:View xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:view="http://davidmoten.homeip.net/uml/executable/view" xsi:schemaLocation="http://davidmoten.homeip.net/uml/executable/view http://xuml-compiler.googlecode.com/svn/trunk/xUmlCompiler/src/viewer/model/viewer.ecore">
  <frame width="902" height="512" x="82" y="183"/>
  <viewport width="1" height="1"/>
  <element x="32" y="220" name="class.Customer"/>
  <element x="249" y="258" name="label.Class Customer Association R1 Verb Clause" fixedTo="//@element[name='class.Customer']"/>
  <element x="248" y="278" name="label.Class Customer Association R1 Multiplicity" fixedTo="//@element[name='class.Customer']"/>
  <element x="367" y="221" name="class.Order"/>
  <element x="519" y="258" name="label.Class Order Association R2 Verb Clause" fixedTo="//@element[name='class.Order']"/>
  <element x="334" y="257" name="label.Class Order Association R1 Verb Clause" fixedTo="//@element[name='class.Order']"/>
  <element x="372" y="188" name="label.Class Order Association R3 Verb Clause" fixedTo="//@element[name='class.Order']"/>
  <element x="355" y="281" name="label.Class Order Association R1 Multiplicity" fixedTo="//@element[name='class.Order']"/>
  <element x="449" y="191" name="label.Class Order Association R3 Multiplicity" fixedTo="//@element[name='class.Order']"/>
  <element x="520" y="281" name="label.Class Order Association R2 Multiplicity" fixedTo="//@element[name='class.Order']"/>
  <element x="361" y="29" name="class.Product"/>
  <element x="450" y="87" name="label.Class Product Association R3 Multiplicity" fixedTo="//@element[name='class.Product']"/>
  <element x="392" y="85" name="label.Class Product Association R3 Verb Clause" fixedTo="//@element[name='class.Product']"/>
  <element x="230" y="110" name="class.OrderProduct"/>
  <element x="699" y="152" name="class.Shipment"/>
  <element x="626" y="254" name="label.Class Shipment Association R2 Verb Clause" fixedTo="//@element[name='class.Shipment']"/>
  <element x="674" y="283" name="label.Class Shipment Association R2 Multiplicity" fixedTo="//@element[name='class.Shipment']"/>
  <element x="52" y="182" name="class.Shipment.state.Lost"/>
  <element x="230" y="89" name="class.Shipment.state.BeingPrepared"/>
  <element x="213" y="249" name="class.Order.state.BeingPreparedAndShipped"/>
  <element x="242" y="5" name="class.Order.state.InitialState"/>
  <element x="114" y="241" name="class.Shipment.state.Shipped"/>
  <element x="476" y="74" name="class.Order.state.Delivered"/>
  <element x="253" y="104" name="class.Order.state.Open"/>
  <element x="148" y="142" name="class.Shipment.state.Returned"/>
  <element x="221" y="26" name="class.Shipment.state.InitialState"/>
  <element x="417" y="134" name="class.Shipment.state.Cancelled"/>
  <element x="239" y="305" name="class.Order.state.FinalState"/>
  <element x="464" y="385" name="class.Shipment.state.FinalState"/>
  <element x="121" y="170" name="class.Order.state.Cancelled"/>
  <element x="92" y="322" name="class.Shipment.state.Delivered"/>
  <element x="295" y="341" name="class.Shipment.state.ReadyForShipping"/>
</view:View>
