<?xml version="1.0" encoding="ASCII"?>
<view:View xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:view="http://davidmoten.homeip.net/uml/executable/view" xsi:schemaLocation="http://davidmoten.homeip.net/uml/executable/view http://xuml-compiler.googlecode.com/svn/trunk/xUmlCompiler/src/viewer/model/viewer.ecore">
  <frame width="1084" height="806" x="94" y="96"/>
  <viewport width="750" height="550"/>
  <element x="889" y="582" name="class.Package"/>
  <element x="348" y="457" name="class.Class"/>
  <element x="485" y="510" name="label.Class Class Association R1 Multiplicity" fixedTo="//@element[name='class.Class']"/>
  <element x="260" y="527" name="label.Class Class Association R4 Verb Clause" fixedTo="//@element[name='class.Class']"/>
  <element x="340" y="429" name="label.Class Class Association R7 Multiplicity" fixedTo="//@element[name='class.Class']"/>
  <element x="388" y="495" name="label.Class Class Association R3 Verb Clause" fixedTo="//@element[name='class.Class']"/>
  <element x="519" y="487" name="label.Class Class Association R11 Multiplicity" fixedTo="//@element[name='class.Class']"/>
  <element x="462" y="458" name="label.Class Class Association R1 Verb Clause" fixedTo="//@element[name='class.Class']"/>
  <element x="568" y="419" name="label.Class Class Association R11 Verb Clause" fixedTo="//@element[name='class.Class']"/>
  <element x="485" y="458" name="label.Class Class Association R3 Multiplicity" fixedTo="//@element[name='class.Class']"/>
  <element x="346" y="506" name="label.Class Class Association R4 Multiplicity" fixedTo="//@element[name='class.Class']"/>
  <element x="270" y="414" name="label.Class Class Association R7 Verb Clause" fixedTo="//@element[name='class.Class']"/>
  <element x="342" y="34" name="class.Association"/>
  <element x="451" y="-287" name="label.Class Association Association R8 Verb Clause" fixedTo="//@element[name='class.Association']"/>
  <element x="307" y="70" name="label.Class Association Association R10 Verb Clause" fixedTo="//@element[name='class.Association']"/>
  <element x="369" y="80" name="label.Class Association Association R10 Multiplicity" fixedTo="//@element[name='class.Association']"/>
  <element x="454" y="23" name="label.Class Association Association R9 Verb Clause" fixedTo="//@element[name='class.Association']"/>
  <element x="460" y="51" name="label.Class Association Association R9 Multiplicity" fixedTo="//@element[name='class.Association']"/>
  <element x="419" y="72" name="label.Class Association Association R8 Multiplicity" fixedTo="//@element[name='class.Association']"/>
  <element x="345" y="296" name="class.AssociationEnd"/>
  <element x="409" y="331" name="label.Class AssociationEnd Association R11 Multiplicity" fixedTo="//@element[name='class.AssociationEnd']"/>
  <element x="318" y="328" name="label.Class AssociationEnd Association R11 Verb Clause" fixedTo="//@element[name='class.AssociationEnd']"/>
  <element x="443" y="208" name="class.AssociationEndPrimary"/>
  <element x="428" y="176" name="label.Class AssociationEndPrimary Association R9 Verb Clause" fixedTo="//@element[name='class.AssociationEndPrimary']"/>
  <element x="522" y="175" name="label.Class AssociationEndPrimary Association R9 Multiplicity" fixedTo="//@element[name='class.AssociationEndPrimary']"/>
  <element x="192" y="210" name="class.AssociationEndSecondary"/>
  <element x="292" y="176" name="label.Class AssociationEndSecondary Association R10 Multiplicity" fixedTo="//@element[name='class.AssociationEndSecondary']"/>
  <element x="198" y="175" name="label.Class AssociationEndSecondary Association R10 Verb Clause" fixedTo="//@element[name='class.AssociationEndSecondary']"/>
  <element x="589" y="418" name="class.Attribute"/>
  <element x="-168" y="151" name="label.Class Attribute Association R1 Multiplicity" fixedTo="//@element[name='class.Attribute']"/>
  <element x="628" y="451" name="label.Class Attribute Association R12 Verb Clause" fixedTo="//@element[name='class.Attribute']"/>
  <element x="600" y="452" name="label.Class Attribute Association R12 Multiplicity" fixedTo="//@element[name='class.Attribute']"/>
  <element x="-112" y="134" name="label.Class Attribute Association R1 Verb Clause" fixedTo="//@element[name='class.Attribute']"/>
  <element x="815" y="379" name="class.AttributeNormal"/>
  <element x="813" y="476" name="class.AttributeReferential"/>
  <element x="27" y="448" name="class.Operation"/>
  <element x="140" y="439" name="label.Class Operation Association R3 Verb Clause" fixedTo="//@element[name='class.Operation']"/>
  <element x="143" y="462" name="label.Class Operation Association R3 Multiplicity" fixedTo="//@element[name='class.Operation']"/>
  <element x="478" y="561" name="class.Identifier"/>
  <element x="187" y="-104" name="label.Class Identifier Association R4 Verb Clause" fixedTo="//@element[name='class.Identifier']"/>
  <element x="543" y="528" name="label.Class Identifier Association R12 Verb Clause" fixedTo="//@element[name='class.Identifier']"/>
  <element x="576" y="528" name="label.Class Identifier Association R12 Multiplicity" fixedTo="//@element[name='class.Identifier']"/>
  <element x="204" y="-49" name="label.Class Identifier Association R4 Multiplicity" fixedTo="//@element[name='class.Identifier']"/>
  <element x="452" y="646" name="class.IdentifierPrimary"/>
  <element x="261" y="643" name="class.IdentifierNonPrimary"/>
  <element x="15" y="365" name="class.SpecializationGroup"/>
  <element x="144" y="393" name="label.Class SpecializationGroup Association R7 Multiplicity" fixedTo="//@element[name='class.SpecializationGroup']"/>
  <element x="144" y="367" name="label.Class SpecializationGroup Association R7 Verb Clause" fixedTo="//@element[name='class.SpecializationGroup']"/>
  <element x="639" y="35" name="class.AssociationClass"/>
  <element x="562" y="23" name="label.Class AssociationClass Association R8 Verb Clause" fixedTo="//@element[name='class.AssociationClass']"/>
  <element x="609" y="47" name="label.Class AssociationClass Association R8 Multiplicity" fixedTo="//@element[name='class.AssociationClass']"/>
</view:View>
